# Generated by Django 5.2.1 on 2025-06-03 15:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTable',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(default=datetime.time(18, 0))),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.TextField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('password_hash', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='event_images/')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.eventtable')),
            ],
        ),
        migrations.AddField(
            model_name='eventtable',
            name='host_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_id', to='core.user'),
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventtable')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'unique_together': {('event_id', 'user_id')},
            },
        ),
    ]
