# Generated by Django 5.2.1 on 2025-05-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=100)),
                ('signups', models.PositiveIntegerField(default=0)),
                ('distance', models.FloatField(help_text='Distance in miles or kilometers')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
