# Generated by Django 5.2.1 on 2025-05-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSignUpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.IntegerField()),
                ('signUps', models.IntegerField()),
                ('signedUp', models.BooleanField()),
            ],
            options={
                'db_table': 'EventSignUp',
            },
        ),
    ]
