# Generated by Django 5.2.1 on 2025-06-03 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_id', models.TextField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('password_hash', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='attendee',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usertable'),
        ),
        migrations.AlterField(
            model_name='eventtable',
            name='host_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_id', to='core.usertable'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
