# Generated by Django 5.2.1 on 2025-06-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usertable_alter_attendee_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='eventimage',
            old_name='event_id',
            new_name='event',
        ),
    ]
