# Generated by Django 5.2.1 on 2025-06-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_eventtable_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.URLField(),
        ),
    ]
