# Generated by Django 5.2.1 on 2025-06-03 15:01

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EventTable',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(default=datetime.time(18, 0))),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='event_images/')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.eventtable')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('password_hash', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='ExampleTableModel',
        ),
        migrations.AddField(
            model_name='attendee',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventtable'),
        ),
        migrations.AddField(
            model_name='eventtable',
            name='host_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_id', to='core.user'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('event_id', 'user_id')},
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.eventtable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
