# Generated by Django 5.2.1 on 2025-06-03 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendee_eventtable_eventimage_user_delete_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventtable'),
        ),
    ]
