# Generated by Django 5.2.1 on 2025-06-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_eventimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtable',
            name='distance',
            field=models.FloatField(default=1.9),
        ),
    ]
