# Generated by Django 5.2.1 on 2025-06-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bookmark_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='event',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('event_id', 'user_id')},
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
