# Generated by Django 5.2.1 on 2025-06-04 19:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_eventtable_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtable',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='eventtable',
            name='distance',
            field=models.FloatField(default=core.models.generate_random_distance),
        ),
    ]
