# Generated by Django 5.2.1 on 2025-06-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_event_bookmark_event_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
