# Generated by Django 5.2.1 on 2025-06-09 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_cohost', to='core.eventtable')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_host', to='core.usertable')),
            ],
            options={
                'unique_together': {('event', 'host')},
            },
        ),
    ]
