# Generated by Django 5.2.1 on 2025-06-11 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_community_eventtable_over_communityimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('event', 'Event')], default='text', max_length=10)),
                ('text', models.TextField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.community')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventtable')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usertable')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
