# Generated by Django 5.2.1 on 2025-06-12 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_communitymessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMessageImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.communitymessage')),
            ],
        ),
    ]
